-- ==============================================================================
-- Gnoteca - Supabase Database Schema & Business Triggers
-- ==============================================================================

-- 1. Tabela de Perfis Públicos (vinculada ao auth.users)
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    display_name text not null,
    avatar_url text,
    current_title text not null default 'Explorador de Conhecimento',
    created_at timestamptz not null default now()
);

-- 2. Tabela de Fragmentos / Pensamentos
create table if not exists public.entries (
    id bigint generated by default as identity primary key,
    author_id uuid not null references public.profiles(id) on delete cascade,
    content text not null check (char_length(trim(content)) between 1 and 280),
    tag text not null default 'Geral',
    parent_id bigint references public.entries(id) on delete cascade,
    dialectic_type text check (dialectic_type in ('antithesis', 'synthesis')),
    created_at timestamptz not null default now()
);

-- 3. Tabela de Votos (Upvotes e Downvotes)
create table if not exists public.votes (
    entry_id bigint not null references public.entries(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    vote_type text not null check (vote_type in ('up', 'down')),
    created_at timestamptz not null default now(),
    primary key (entry_id, user_id)
);

-- 4. Tabela de Favoritos (Constelação de 3 pilares)
create table if not exists public.favorites (
    entry_id bigint not null references public.entries(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (entry_id, user_id)
);

-- 5. Índices para Alta Performance
create index if not exists entries_created_at_idx on public.entries (created_at desc);
create index if not exists entries_author_id_idx on public.entries (author_id);
create index if not exists entries_tag_idx on public.entries (tag);
create index if not exists entries_parent_id_idx on public.entries (parent_id);
create index if not exists votes_entry_id_idx on public.votes (entry_id);
create index if not exists favorites_entry_id_idx on public.favorites (entry_id);

-- 6. Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.entries enable row level security;
alter table public.votes enable row level security;
alter table public.favorites enable row level security;

-- Políticas de Acesso para Profiles
drop policy if exists "Profiles are public" on public.profiles;
create policy "Profiles are public" on public.profiles for select using (true);

drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Políticas de Acesso para Entries
drop policy if exists "Entries are public" on public.entries;
create policy "Entries are public" on public.entries for select using (true);

drop policy if exists "Authenticated users can create entries" on public.entries;
create policy "Authenticated users can create entries" on public.entries for insert to authenticated with check (auth.uid() = author_id);

drop policy if exists "Authors can update entries" on public.entries;
create policy "Authors can update entries" on public.entries for update using (auth.uid() = author_id) with check (auth.uid() = author_id);

drop policy if exists "Authors can delete entries" on public.entries;
create policy "Authors can delete entries" on public.entries for delete using (auth.uid() = author_id);

-- Políticas de Acesso para Votes
drop policy if exists "Votes are public" on public.votes;
create policy "Votes are public" on public.votes for select using (true);

drop policy if exists "Users manage their votes" on public.votes;
create policy "Users manage their votes" on public.votes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Políticas de Acesso para Favorites
drop policy if exists "Favorites are public" on public.favorites;
create policy "Favorites are public" on public.favorites for select using (true);

drop policy if exists "Users manage their favorites" on public.favorites;
create policy "Users manage their favorites" on public.favorites for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 7. Trigger: Criação Automática de Perfil no Cadastro (incluindo Avatar Google)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, username, display_name, avatar_url)
    values (
        new.id,
        lower(regexp_replace(coalesce(new.raw_user_meta_data->>'user_name', split_part(new.email, '@', 1)), '[^a-zA-Z0-9]+', '-', 'g')),
        coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', new.email),
        coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture')
    )
    on conflict (id) do update set
        avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
        display_name = coalesce(excluded.display_name, profiles.display_name);
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- 8. Trigger: Limite de favoritos por progressão de pensador
create or replace function public.check_max_favorites()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    fav_count int;
    entry_count int;
    max_favs int := 3;
begin
    -- Conta fragmentos publicados pelo usuário
    select count(*) into entry_count
    from public.entries
    where author_id = new.user_id;

    -- Define limite por progressão
    if entry_count >= 50 then
        max_favs := 15;
    elsif entry_count >= 25 then
        max_favs := 10;
    elsif entry_count >= 10 then
        max_favs := 7;
    elsif entry_count >= 3 then
        max_favs := 5;
    else
        max_favs := 3;
    end if;

    -- Conta favoritos atuais
    select count(*) into fav_count
    from public.favorites
    where user_id = new.user_id;

    if fav_count >= max_favs then
        raise exception 'Limite de % favoritos atingido para o seu nível.', max_favs;
    end if;
    return new;
end;
$$;

drop trigger if exists enforce_max_favorites on public.favorites;
create trigger enforce_max_favorites
before insert on public.favorites
for each row execute procedure public.check_max_favorites();

-- 9. Trigger: Limite de no máximo 5 votos diários por pensador
create or replace function public.check_max_daily_votes()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    vote_count int;
begin
    select count(*) into vote_count
    from public.votes
    where user_id = new.user_id
      and created_at >= date_trunc('day', now());

    if vote_count >= 5 then
        raise exception 'Limite de 5 votos diários atingido.';
    end if;
    return new;
end;
$$;

drop trigger if exists enforce_max_daily_votes on public.votes;
create trigger enforce_max_daily_votes
before insert on public.votes
for each row execute procedure public.check_max_daily_votes();

-- ==============================================================================
-- 7. TABELA DE NOTIFICAÇÕES (NOTIFICATIONS) E GATILHOS AUTOMÁTICOS
-- ==============================================================================

create table if not exists public.notifications (
    id bigint generated always as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    actor_id uuid not null references auth.users(id) on delete cascade,
    type text not null check (type in ('vote_up', 'favorite', 'comment', 'reply')),
    entry_id bigint references public.entries(id) on delete cascade,
    read boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists notifications_user_id_idx on public.notifications(user_id, read, created_at desc);
create index if not exists notifications_entry_id_idx on public.notifications(entry_id);

alter table public.notifications enable row level security;

create policy "Usuários podem ver suas próprias notificações"
on public.notifications for select
using (auth.uid() = user_id);

create policy "Usuários podem atualizar suas próprias notificações"
on public.notifications for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuários autenticados podem criar notificações"
on public.notifications for insert
with check (auth.uid() = actor_id);

-- Gatilho de Voto (Upvote)
create or replace function public.handle_vote_notification()
returns trigger as $$
declare
    target_author_id uuid;
begin
    if new.vote_type = 'up' then
        select author_id into target_author_id from public.entries where id = new.entry_id;
        if target_author_id is not null and target_author_id <> new.user_id then
            insert into public.notifications (user_id, actor_id, type, entry_id)
            values (target_author_id, new.user_id, 'vote_up', new.entry_id);
        end if;
    end if;
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trigger_notify_vote on public.votes;
create trigger trigger_notify_vote
after insert on public.votes
for each row
execute function public.handle_vote_notification();

-- Gatilho de Favorito
create or replace function public.handle_favorite_notification()
returns trigger as $$
declare
    target_author_id uuid;
begin
    select author_id into target_author_id from public.entries where id = new.entry_id;
    if target_author_id is not null and target_author_id <> new.user_id then
        insert into public.notifications (user_id, actor_id, type, entry_id)
        values (target_author_id, new.user_id, 'favorite', new.entry_id);
    end if;
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trigger_notify_favorite on public.favorites;
create trigger trigger_notify_favorite
after insert on public.favorites
for each row
execute function public.handle_favorite_notification();

-- Gatilho de Comentário / Resposta
create or replace function public.handle_entry_notification()
returns trigger as $$
declare
    target_author_id uuid;
    parent_has_parent bigint;
    notif_type text;
begin
    if new.parent_id is not null then
        select author_id, parent_id into target_author_id, parent_has_parent 
        from public.entries where id = new.parent_id;

        if target_author_id is not null and target_author_id <> new.author_id then
            notif_type := case when parent_has_parent is not null then 'reply' else 'comment' end;
            insert into public.notifications (user_id, actor_id, type, entry_id)
            values (target_author_id, new.author_id, notif_type, new.id);
        end if;
    end if;
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trigger_notify_entry on public.entries;
create trigger trigger_notify_entry
after insert on public.entries
for each row
execute function public.handle_entry_notification();

-- ==============================================================================
-- Migração Fase 2: Escalabilidade e Velocidade (Zero JS Sorting)
-- ==============================================================================

-- 1. Criação da Tabela de Contagem de Tópicos
CREATE TABLE IF NOT EXISTS public.topic_counts (
    tag text primary key,
    entry_count integer not null default 0,
    updated_at timestamptz not null default now()
);

-- Habilitar RLS na nova tabela
ALTER TABLE public.topic_counts ENABLE ROW LEVEL SECURITY;

-- Política de leitura pública para topic_counts
DROP POLICY IF EXISTS "Topic counts are public" ON public.topic_counts;
CREATE POLICY "Topic counts are public" ON public.topic_counts FOR SELECT USING (true);

-- 2. Adição de Colunas de Contagem Desnormalizadas na tabela `entries`
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS upvotes_count integer not null default 0;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS downvotes_count integer not null default 0;
ALTER TABLE public.entries ADD COLUMN IF NOT EXISTS favorites_count integer not null default 0;

-- 3. Índices para ordenação no Banco de Dados
CREATE INDEX IF NOT EXISTS entries_upvotes_count_idx ON public.entries (upvotes_count DESC);
CREATE INDEX IF NOT EXISTS entries_favorites_count_idx ON public.entries (favorites_count DESC);
CREATE INDEX IF NOT EXISTS topic_counts_count_idx ON public.topic_counts (entry_count DESC);

-- ==============================================================================
-- Triggers e Funções de Sincronização
-- ==============================================================================

-- 4. Função para manter a contagem de Tópicos
CREATE OR REPLACE FUNCTION public.sync_topic_counts()
RETURNS trigger AS $$
BEGIN
    -- Se for INSERT e for um post raiz (não for comentário)
    IF TG_OP = 'INSERT' AND NEW.parent_id IS NULL THEN
        INSERT INTO public.topic_counts (tag, entry_count)
        VALUES (NEW.tag, 1)
        ON CONFLICT (tag) DO UPDATE 
        SET entry_count = public.topic_counts.entry_count + 1,
            updated_at = now();
    
    -- Se for DELETE e for um post raiz
    ELSIF TG_OP = 'DELETE' AND OLD.parent_id IS NULL THEN
        UPDATE public.topic_counts 
        SET entry_count = entry_count - 1,
            updated_at = now()
        WHERE tag = OLD.tag;

        -- Limpa tópicos vazios (opcional)
        DELETE FROM public.topic_counts WHERE entry_count <= 0;
        
    -- Se a tag mudou (UPDATE)
    ELSIF TG_OP = 'UPDATE' AND NEW.parent_id IS NULL AND OLD.tag IS DISTINCT FROM NEW.tag THEN
        -- Subtrai da antiga
        UPDATE public.topic_counts 
        SET entry_count = entry_count - 1,
            updated_at = now()
        WHERE tag = OLD.tag;
        
        -- Soma na nova
        INSERT INTO public.topic_counts (tag, entry_count)
        VALUES (NEW.tag, 1)
        ON CONFLICT (tag) DO UPDATE 
        SET entry_count = public.topic_counts.entry_count + 1,
            updated_at = now();
            
        -- Limpa tópicos vazios
        DELETE FROM public.topic_counts WHERE entry_count <= 0;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_sync_topic_counts ON public.entries;
CREATE TRIGGER trigger_sync_topic_counts
AFTER INSERT OR UPDATE OR DELETE ON public.entries
FOR EACH ROW EXECUTE FUNCTION public.sync_topic_counts();

-- 5. Função para manter a contagem de Votos (Upvotes / Downvotes)
CREATE OR REPLACE FUNCTION public.sync_vote_counts()
RETURNS trigger AS $$
BEGIN
    -- INSERT
    IF TG_OP = 'INSERT' THEN
        IF NEW.vote_type = 'up' THEN
            UPDATE public.entries SET upvotes_count = upvotes_count + 1 WHERE id = NEW.entry_id;
        ELSIF NEW.vote_type = 'down' THEN
            UPDATE public.entries SET downvotes_count = downvotes_count + 1 WHERE id = NEW.entry_id;
        END IF;
        
    -- DELETE
    ELSIF TG_OP = 'DELETE' THEN
        IF OLD.vote_type = 'up' THEN
            UPDATE public.entries SET upvotes_count = upvotes_count - 1 WHERE id = OLD.entry_id;
        ELSIF OLD.vote_type = 'down' THEN
            UPDATE public.entries SET downvotes_count = downvotes_count - 1 WHERE id = OLD.entry_id;
        END IF;
        
    -- UPDATE (usuário mudou de UP para DOWN ou vice-versa)
    ELSIF TG_OP = 'UPDATE' AND OLD.vote_type IS DISTINCT FROM NEW.vote_type THEN
        IF NEW.vote_type = 'up' THEN
            UPDATE public.entries SET 
                upvotes_count = upvotes_count + 1,
                downvotes_count = downvotes_count - 1
            WHERE id = NEW.entry_id;
        ELSIF NEW.vote_type = 'down' THEN
            UPDATE public.entries SET 
                upvotes_count = upvotes_count - 1,
                downvotes_count = downvotes_count + 1
            WHERE id = NEW.entry_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_sync_vote_counts ON public.votes;
CREATE TRIGGER trigger_sync_vote_counts
AFTER INSERT OR UPDATE OR DELETE ON public.votes
FOR EACH ROW EXECUTE FUNCTION public.sync_vote_counts();


-- 6. Função para manter a contagem de Favoritos
CREATE OR REPLACE FUNCTION public.sync_favorite_counts()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.entries SET favorites_count = favorites_count + 1 WHERE id = NEW.entry_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE public.entries SET favorites_count = favorites_count - 1 WHERE id = OLD.entry_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_sync_favorite_counts ON public.favorites;
CREATE TRIGGER trigger_sync_favorite_counts
AFTER INSERT OR DELETE ON public.favorites
FOR EACH ROW EXECUTE FUNCTION public.sync_favorite_counts();
