create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    display_name text not null,
    avatar_url text,
    created_at timestamptz not null default now()
);

create table public.entries (
    id bigint generated by default as identity primary key,
    author_id uuid not null references public.profiles(id) on delete cascade,
    content text not null check (char_length(trim(content)) between 1 and 280),
    created_at timestamptz not null default now()
);

create table public.votes (
    entry_id bigint not null references public.entries(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    vote_type text not null check (vote_type in ('up', 'down')),
    created_at timestamptz not null default now(),
    primary key (entry_id, user_id)
);

create table public.favorites (
    entry_id bigint not null references public.entries(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (entry_id, user_id)
);

create index entries_created_at_idx on public.entries (created_at desc);
create index entries_author_id_idx on public.entries (author_id);
create index votes_entry_id_idx on public.votes (entry_id);
create index favorites_entry_id_idx on public.favorites (entry_id);

alter table public.profiles enable row level security;
alter table public.entries enable row level security;
alter table public.votes enable row level security;
alter table public.favorites enable row level security;

create policy "Profiles are public" on public.profiles
    for select using (true);
create policy "Users can create their profile" on public.profiles
    for insert with check (auth.uid() = id);
create policy "Users can update their profile" on public.profiles
    for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Entries are public" on public.entries
    for select using (true);
create policy "Authenticated users can create entries" on public.entries
    for insert to authenticated with check (auth.uid() = author_id);
create policy "Authors can update entries" on public.entries
    for update using (auth.uid() = author_id) with check (auth.uid() = author_id);
create policy "Authors can delete entries" on public.entries
    for delete using (auth.uid() = author_id);

create policy "Votes are public" on public.votes
    for select using (true);
create policy "Users manage their votes" on public.votes
    for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Favorites are public" on public.favorites
    for select using (true);
create policy "Users manage their favorites" on public.favorites
    for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, username, display_name)
    values (
        new.id,
        lower(regexp_replace(coalesce(new.raw_user_meta_data->>'user_name', split_part(new.email, '@', 1)), '[^a-zA-Z0-9]+', '-', 'g')),
        coalesce(new.raw_user_meta_data->>'full_name', new.email)
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

create or replace trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

