-- ==============================================================================
-- Gnoteca - Supabase Database Schema & Business Triggers
-- ==============================================================================

-- 1. Tabela de Perfis Públicos (vinculada ao auth.users)
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    display_name text not null,
    avatar_url text,
    current_title text not null default 'Explorador de Conhecimento',
    created_at timestamptz not null default now()
);

-- 2. Tabela de Fragmentos / Pensamentos
create table if not exists public.entries (
    id bigint generated by default as identity primary key,
    author_id uuid not null references public.profiles(id) on delete cascade,
    content text not null check (char_length(trim(content)) between 1 and 280),
    tag text not null default 'Geral',
    created_at timestamptz not null default now()
);

-- 3. Tabela de Votos (Upvotes e Downvotes)
create table if not exists public.votes (
    entry_id bigint not null references public.entries(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    vote_type text not null check (vote_type in ('up', 'down')),
    created_at timestamptz not null default now(),
    primary key (entry_id, user_id)
);

-- 4. Tabela de Favoritos (Constelação de 3 pilares)
create table if not exists public.favorites (
    entry_id bigint not null references public.entries(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (entry_id, user_id)
);

-- 5. Índices para Alta Performance
create index if not exists entries_created_at_idx on public.entries (created_at desc);
create index if not exists entries_author_id_idx on public.entries (author_id);
create index if not exists entries_tag_idx on public.entries (tag);
create index if not exists votes_entry_id_idx on public.votes (entry_id);
create index if not exists favorites_entry_id_idx on public.favorites (entry_id);

-- 6. Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.entries enable row level security;
alter table public.votes enable row level security;
alter table public.favorites enable row level security;

-- Políticas de Acesso para Profiles
drop policy if exists "Profiles are public" on public.profiles;
create policy "Profiles are public" on public.profiles for select using (true);

drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Políticas de Acesso para Entries
drop policy if exists "Entries are public" on public.entries;
create policy "Entries are public" on public.entries for select using (true);

drop policy if exists "Authenticated users can create entries" on public.entries;
create policy "Authenticated users can create entries" on public.entries for insert to authenticated with check (auth.uid() = author_id);

drop policy if exists "Authors can update entries" on public.entries;
create policy "Authors can update entries" on public.entries for update using (auth.uid() = author_id) with check (auth.uid() = author_id);

drop policy if exists "Authors can delete entries" on public.entries;
create policy "Authors can delete entries" on public.entries for delete using (auth.uid() = author_id);

-- Políticas de Acesso para Votes
drop policy if exists "Votes are public" on public.votes;
create policy "Votes are public" on public.votes for select using (true);

drop policy if exists "Users manage their votes" on public.votes;
create policy "Users manage their votes" on public.votes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Políticas de Acesso para Favorites
drop policy if exists "Favorites are public" on public.favorites;
create policy "Favorites are public" on public.favorites for select using (true);

drop policy if exists "Users manage their favorites" on public.favorites;
create policy "Users manage their favorites" on public.favorites for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 7. Trigger: Criação Automática de Perfil no Cadastro (incluindo Avatar Google)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, username, display_name, avatar_url)
    values (
        new.id,
        lower(regexp_replace(coalesce(new.raw_user_meta_data->>'user_name', split_part(new.email, '@', 1)), '[^a-zA-Z0-9]+', '-', 'g')),
        coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', new.email),
        coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture')
    )
    on conflict (id) do update set
        avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
        display_name = coalesce(excluded.display_name, profiles.display_name);
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- 8. Trigger: Limite de favoritos por progressão de pensador
create or replace function public.check_max_favorites()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    fav_count int;
    entry_count int;
    max_favs int := 3;
begin
    -- Conta fragmentos publicados pelo usuário
    select count(*) into entry_count
    from public.entries
    where author_id = new.user_id;

    -- Define limite por progressão
    if entry_count >= 50 then
        max_favs := 15;
    elsif entry_count >= 25 then
        max_favs := 10;
    elsif entry_count >= 10 then
        max_favs := 7;
    elsif entry_count >= 3 then
        max_favs := 5;
    else
        max_favs := 3;
    end if;

    -- Conta favoritos atuais
    select count(*) into fav_count
    from public.favorites
    where user_id = new.user_id;

    if fav_count >= max_favs then
        raise exception 'Limite de % favoritos atingido para o seu nível.', max_favs;
    end if;
    return new;
end;
$$;

drop trigger if exists enforce_max_favorites on public.favorites;
create trigger enforce_max_favorites
before insert on public.favorites
for each row execute procedure public.check_max_favorites();

-- 9. Trigger: Limite de no máximo 5 votos diários por pensador
create or replace function public.check_max_daily_votes()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    vote_count int;
begin
    select count(*) into vote_count
    from public.votes
    where user_id = new.user_id
      and created_at >= date_trunc('day', now());

    if vote_count >= 5 then
        raise exception 'Limite de 5 votos diários atingido.';
    end if;
    return new;
end;
$$;

drop trigger if exists enforce_max_daily_votes on public.votes;
create trigger enforce_max_daily_votes
before insert on public.votes
for each row execute procedure public.check_max_daily_votes();
